language: rust
dist: focal
cache:
  ccache: true
  cargo: true

rust:
  - stable
  - beta

addons:
  apt:
    packages:
      - gcc
      - libc6-dev
      - ca-certificates
      - libsystemd-dev
      - pkg-config

script:
  - ci/script-1

branches:
  only:
    - staging
    - trying
    - master
